
[env:esp32-s3-devkitc-1-Modded]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = max_app_8MB.csv

framework = arduino

upload_port = COM27   ;Serial
;upload_port = COM7   ;Serial
monitor_port = COM27  ;Serial
;monitor_port = COM7  ;Serial


monitor_speed = 921600
debug_init_break = tbreak setup
debug_tool = esp-builtin
debug_speed = 10000
;debug_build_flags = -O0
;debug_build_flags = -g3

board_build.arduino.memory_type = dio_opi
build_flags = 
    -Os
    -DBOARD_HAS_PSRAM
    -D FW_VERSION=\"0.0.0-beta.1\"
    -DCONFIG_MBEDTLS_DYNAMIC_BUFFER=1
debug_extra_cmds =
    set output-radix 16
    

