
[env:esp32-s3-devkitc-1-Modded]
;Arduino 2.XX and ESP32IDF prior to IDF 5.x is requiered.
platform = espressif32@6.11.0 ;Must lock to this version or many includes will not work in the new Arduino version
board = esp32-s3-devkitc-1
board_build.partitions = min_spiffs.csv

# Name,   Type, SubType, Offset,  Size, Flags
;nvs,      data, nvs,     0x9000,  0x5000,
;otadata,  data, ota,     0xe000,  0x2000,
;app0,     app,  ota_0,   0x10000, 0x1E0000,
;app1,     app,  ota_1,   0x1F0000,0x1E0000,
;spiffs,   data, spiffs,  0x3D0000,0x20000,
;coredump, data, coredump,0x3F0000,0x10000,

framework = arduino

upload_port = COM5   ;Serial Port of your device here for upload
monitor_port = COM5  ;Serial Port of your device here for Monitor


monitor_speed = 921600
debug_init_break = tbreak setup
debug_tool = esp-builtin
debug_speed = 10000
;debug_build_flags = -O0
;debug_build_flags = -g3

board_build.arduino.memory_type = dio_opi
build_flags = 
    -Os
    -DBOARD_HAS_PSRAM
    -D FW_VERSION=\"0.0.0-beta.1\"
    -DCONFIG_MBEDTLS_DYNAMIC_BUFFER=1
debug_extra_cmds =
    set output-radix 16
    

